---
- name: update apt
  apt: update_cache=yes cache_valid_time=3600

- name: install deps
  apt: pkg={{ item }} state=installed
  with_items:
    - unzip
    - jq

- name: Check consul already installed
  stat: path={{ consul_dest_dir }}/consul
  register: consul_status

- include: install.yml
  when: consul_status.stat.exists == false or consul_force_install

- name: Start consul service
  service: name=consul state=started

- name: Check porter installed
  command: "{{ porter_dest_dir }}/porter version"
  register: current_porter_version
  changed_when: current_porter_version.stdout.strip() != porter_version

- name: Install porter if not
  include: porter.yml
  when: current_porter_version.stdout.strip() != porter_version
