---
- name: update apt
  apt: update_cache=yes cache_valid_time=3600

- name: install deps
  apt: pkg={{ item }} state=installed
  with_items:
    - unzip
    - jq

- name: Check consul already installed
  stat: path={{ consul_dest_dir }}/consul
  register: consul_status

- include: install.yml
  when: consul_status.stat.exists == false or consul_force_install

- name: Start consul service
  service: name=consul state=started
