---
consul_version: 0.5.0
consul_archive: {{ consul_version }}_linux_amd64.zip
consul_ui_archive: {{ consul_version }}_web_ui.zip
consul_download_url: https://dl.bintray.com/mitchellh/consul/{{ consul_archive }}
consul_ui_download_url: https://dl.bintray.com/mitchellh/consul/{{ consul_ui_archive }}
consul_dest_dir: /usr/local/bin
