---
- name: Repos folder
  file: path="/data/repos" mode=a+rwx state=directory

- name: Build containers if not exists
  include: build_containers.yml
  when: containers is defined

# - name: Run containers (wait until containers is up)
#   debug:

# - name: Update service records in consul
#   debug:

- name: Update nginx config
  include: proxy_config.yml
  notify: Restart nginx
  when: frontend_proxy is defined
